dataset_path: ./dataset/
output_path: ./output/
suggestion:
  kernel_size: 9
  n_conv_steps: 4
  n_filters: 93
  dense_size: 1365
  final_lr: 0.000004520
  dropout: 0.3608
  n_filters_customsum: 12
  kernel_size_customsum: 4
